// chat-client-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import {
  ObservableEvents,
  ObservableService,
} from './services/observable.service';
import { SocketService } from './services/socket.service';

interface IMessage {
  id: string;
  name: string;
  content: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  joined: boolean = false;
  messages: IMessage[] = [];
  messageToSend: string = '';
  userName: string = '';
  typingDisplay = '';

  constructor(
    private socketService: SocketService,
    private observableService: ObservableService
  ) {}

  ngOnInit(): void {
    this.socketService.init();

    this.socketService.emitFindAllMessages((allMessages: IMessage[]) => {
      this.messages = allMessages;
    });

    this._messageListener();
    this._typingListener();
  }

  join(): void {
    if (this.userName !== '') {
      this.socketService.emitJoin(this.userName, () => {
        this.joined = true;
      });
    }
  }

  sendMessage(): void {
    if (this.messageToSend !== '') {
      this.socketService.emitSendMessage(this.messageToSend, () => {
        this.messageToSend = '';
      });
    }
  }

  inputTyping(): void {
    this.socketService.emitTyping(true);
    setTimeout(() => {
      this.socketService.emitTyping(false);
    }, 2000);
  }

  private _messageListener(): void {
    this.observableService.currentMessage.subscribe((message) => {
      if (message.event === ObservableEvents.message) {
        this.messages.push(message.payload);
      }
    });
  }

  private _typingListener(): void {
    this.observableService.currentMessage.subscribe((message) => {
      if (message.event === ObservableEvents.typing) {
        if (message.payload.isTyping) {
          this.typingDisplay = `${message.payload.name} is typing...`;
        } else {
          this.typingDisplay = '';
        }
      }
    });
  }
}

<div class="chat">
  <div>
    <form *ngIf="!joined">
      <label for="name">What's your name? </label>
      <input id="name" name="name" [(ngModel)]="userName" #name="ngModel" />
      <button (click)="join()">Send</button>
    </form>
  </div>
  <div class="chat-container" *ngIf="joined">
    <div class="messages-container">
      <div *ngFor="let message of messages">
        [{{ message.name }}]:
        {{ message.content }}
      </div>
    </div>
  </div>
</div>

<div *ngIf="typingDisplay">{{ typingDisplay }}</div>

<div *ngIf="joined" class="message-input">
  <hr />
  <form>
    <label for="message">Message:</label>
    <input
      id="messageToSend"
      name="messageToSend"
      [(ngModel)]="messageToSend"
      #name="ngModel"
      (input)="inputTyping()"
    />
    <button (click)="sendMessage()">Send</button>
  </form>
</div>

// chat-client-vuejs/src/App.vue
<script setup>
import { io } from 'socket.io-client';
import { onBeforeMount, ref } from 'vue';

const socket = io('http://localhost:3333');

const messages = ref([]);
const messageContent = ref('');
const joined = ref(false);
const name = ref('');
const typingDisplay = ref('');

onBeforeMount(() => {
  socket.emit('findAllMessages', {}, (response) => {
    messages.value = response;
  });

  socket.on('message', (message) => {
    messages.value.push(message);
  });

  socket.on('typing', ({ name, isTyping }) => {
    if (isTyping) {
      typingDisplay.value = `${name} is typing...`;
    } else {
      typingDisplay.value = '';
    }
  });
});

const sendMessage = () => {
  socket.emit('createMessage', { content: messageContent.value }, () => {
    messageContent.value = '';
  });
};

const join = () => {
  socket.emit('join', { name: name.value }, () => {
    joined.value = true;
  });
};

let timeout;
const emitTyping = () => {
  socket.emit('typing', { isTyping: true });
  timeout = setTimeout(() => {
    socket.emit('typing', { isTyping: false });
  }, 2000);
};
</script>

<template>
  <div class="chat">
    <div v-if="!joined">
      <form @submit.prevent="join">
        <label>What's your name?</label>
        <input v-model="name" />
        <button type="submit">Send</button>
      </form>
    </div>
    <div class="chat-container" v-else>
      <div class="messages-container">
        <div v-for="message in messages">
          [{{ message.name }}]: {{ message.content }}
        </div>
      </div>
    </div>

    <div v-if="typingDisplay">{{ typingDisplay }}</div>

    <hr />

    <div class="message-input">
      <form @submit.prevent="sendMessage">
        <label>Message:</label>
        <input v-model="messageContent" @input="emitTyping" />
        <button type="submit">Send</button>
      </form>
    </div>
  </div>
</template>

<style>
@import './assets/base.css';

.chat {
  padding: 20px;
  height: 100vh;
}

.chat-container {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.messages-container {
  flex: 1;
}
</style>
